---
kind: pipeline
name: default

steps:
  - name: build
    image: node:14
    commands:
      - npm install
      - npm run build

  - name: test
    image: node:14
    commands:
      - npm test

  - name: deploy
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: your-docker-repo/your-app
      tags: latest